### ISSUE TITLE
vagrant up SSL certificate issue

### ISSUE THREAD

**Issue by jkinning** [UtahDave/salt-vagrant-demo#35] opened 2017-01-10 18:59 UTC
$ vagrant up --provider virtualbox
Bringing machine 'master' up with 'virtualbox' provider...
Bringing machine 'minion1' up with 'virtualbox' provider...
Bringing machine 'minion2' up with 'virtualbox' provider...
==> master: Box 'ubuntu/trusty64' could not be found. Attempting to find and install...
    master: Box Provider: virtualbox
    master: Box Version: >= 0
The box 'ubuntu/trusty64' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/ubuntu/trusty64"]
Error: SSL certificate problem: unable to get local issuer certificate
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.

**Comment by UtahDave** [comment] 2017-08-23 19:57
We're using a different box now. 

Does updating curl on your host system fix this?  What OS and version of your OS are you on?

I can't reproduce this at all.

**Comment by UtahDave** [comment] 2017-10-23 18:34
I can't reproduce this. I think upgrading might fix. I'm going to close this. If you're still running into this issue, please comment here and I'll reopen.

Thanks!

**Closed as completed by UtahDave** 2017-10-23 18:34 UTC
