### ISSUE TITLE
Salt not installed

### ISSUE THREAD

**Issue by jlamb85** [UtahDave/salt-vagrant-demo#36] opened 2017-04-10 10:41 UTC
localhost$ vagrant ssh master
Welcome to Ubuntu 14.04.5 LTS (GNU/Linux 3.13.0-116-generic x86_64)

 * Documentation:  https://help.ubuntu.com/

 System information disabled due to load higher than 1.0

  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud

0 packages can be updated.
0 updates are security updates.

New release '16.04.2 LTS' available.
Run 'do-release-upgrade' to upgrade to it.

localhost$ salt
The program 'salt' is currently not installed. To run 'salt' please ask your administrator to install the package 'salt-master'

after install salt-master and running : sudo salt '*' test.ping 
I get the following error: No minions matched the target. No command was sent, no jid was assigned.

**Comment by DanielFallon** [comment] 2017-04-27 16:24
@jlamb85 I was able to fix this by running `vagrant up` a second time.

not ideal, but it seems like for me there is an issue with networking coming up fast enough

**Comment by haseebeqx** [comment] 2017-08-17 09:19
change `Vagrantfile` according to the accepted answer in https://stackoverflow.com/questions/18457306/enable-internet-access-inside-vagrant
and then
do
```bash
vagrant destroy && vagrant up
```
WARNING: it will delete and re import vm

**Comment by UtahDave** [comment] 2017-08-23 19:56
Hi @jlamb85 I haven't been able to reproduce this.  Can you update your clone of the repo and try again?

**Comment by UtahDave** [comment] 2017-09-11 19:35
We've had some updates since this issue was opened. I haven't been able to reproduce, nor have we heard back from the OP. So I'm going to close this issue. Please comment here and I'll reopen if new info is provided.

Thanks

**Closed as completed by UtahDave** 2017-09-11 19:35 UTC
